application: imposing-muse-664
module: batch
version: 0-0-0
runtime: go
api_version: go1
instance_class: B1
basic_scaling:
  max_instances: 20
  idle_timeout: 10m

handlers:
- url: /.*
  script: _go_app
  login: admin
  secure: always
